import Head from 'next/head'
import { Container } from 'react-bootstrap';
import MainHead from './head/MainHead';
import classes from '../styles/Home.module.css';
import SubHead from './subhead/SubHead';

export default function Home() {
  return (
    <>
      <section className={classes.head_container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container >
          <MainHead />
        </Container>
      </section>
      <section className={classes.subhead_container}>
        <Container>
          <SubHead />
        </Container>
      </section>
    </>
  )
}
